# Generated by Django 2.2.5 on 2019-09-24 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billet', '0005_auto_20190907_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billet',
            options={'ordering': ['-dueDate', '-created_at'], 'permissions': [('list_billet', 'Pode Listar Boletos')], 'verbose_name': 'Boleto', 'verbose_name_plural': 'Boletos'},
        ),
    ]
