name: ticket-admin

services:
  admin:
    build: .
    ports:
      - 8001:8000
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - admin-media:/app/media
    networks:
      - admin-net

  postgres:
    image: postgres:alpine
    env_file:
      - .env.db
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - admin-net

networks:
  admin-net:

volumes:
  pg-data:
  admin-media:
