# Generated by Django 2.2.1 on 2019-08-07 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['name', '-created_at'], 'permissions': [('list_profile', 'Pode Listar Perfils')], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfils'},
        ),
    ]
