# Generated by Django 2.2.1 on 2019-09-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cpf',
            field=models.CharField(default='', max_length=11, verbose_name='CPF'),
            preserve_default=False,
        ),
    ]
