# Generated by Django 2.2.1 on 2019-08-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='amount_billet',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='config',
            name='description_billet',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='config',
            name='instructions_billet',
            field=models.CharField(max_length=100, verbose_name='Instruções'),
        ),
    ]
