# Generated by Django 2.2.5 on 2019-09-24 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190807_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': 'Configuração', 'verbose_name_plural': 'Configurações'},
        ),
    ]
