# Generated by Django 2.2.10 on 2020-05-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190923_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='amount_billet',
        ),
    ]
