# Generated by Django 2.2.10 on 2020-05-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_config_amount_billet'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='sandbox',
            field=models.BooleanField(default=True, verbose_name='Sandbox'),
        ),
    ]
