# Generated by Django 2.2.10 on 2020-05-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tutorial_tutorialimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialimage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='tutorialimage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título'),
        ),
    ]
