# Generated by Django 2.2.10 on 2020-05-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200515_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ['order', 'name'], 'permissions': [('list_tutorial', 'Pode Listar Tutoriais')], 'verbose_name': 'Tutorial', 'verbose_name_plural': 'Tutoriais'},
        ),
    ]
