# Generated by Django 2.2.1 on 2019-08-08 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('token', models.CharField(max_length=255, verbose_name='Token')),
                ('instructions_billet', models.CharField(max_length=100, verbose_name='Instruções Geral do Boleto')),
                ('description_billet', models.CharField(max_length=100, verbose_name='Descrição Geral do Boleto')),
                ('amount_billet', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Geral do Boleto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configuração',
            },
        ),
    ]
