# Generated by Django 2.2.1 on 2019-08-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='amount_billet',
            field=models.DecimalField(decimal_places=2, default='10.00', max_digits=15, verbose_name='Valor Geral do Boleto'),
            preserve_default=False,
        ),
    ]
