# Generated by Django 2.2.1 on 2019-08-07 03:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_profile', '0002_auto_20190807_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Código')),
                ('paymentLink', models.URLField(verbose_name='Link de Pagamento')),
                ('barcode', models.CharField(max_length=255, verbose_name='Código de Barras')),
                ('dueDate', models.DateField(verbose_name='Vencimento')),
                ('reference', models.CharField(max_length=200, verbose_name='Referencia')),
                ('firstDueDate', models.DateField(verbose_name='Data de vencimento')),
                ('numberOfPayments', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Parcelas')),
                ('instructions', models.CharField(max_length=100, verbose_name='Instruções')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('recused', 'Recusado')], default='pending', max_length=255, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billets', to='custom_profile.Profile', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
                'permissions': [('list_billet', 'Pode Listar Boletos')],
            },
        ),
    ]
