# Generated by Django 2.2.1 on 2019-08-08 02:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billet',
            name='numberOfPayments',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Períodos mensais'),
        ),
    ]
