# Generated by Django 2.2.1 on 2019-09-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billet', '0002_auto_20190807_2343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billet',
            options={'ordering': ['created_at'], 'permissions': [('list_billet', 'Pode Listar Boletos')], 'verbose_name': 'Boleto', 'verbose_name_plural': 'Boletos'},
        ),
        migrations.RemoveField(
            model_name='billet',
            name='firstDueDate',
        ),
        migrations.AlterField(
            model_name='billet',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='billet',
            name='dueDate',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento'),
        ),
        migrations.AlterField(
            model_name='billet',
            name='status',
            field=models.CharField(choices=[(1, 'Aguardando pagamento'), (2, 'Em análise'), (3, 'Pago'), (4, 'Disponível'), (5, 'Em disputa'), (6, 'Devolvida'), (7, 'Cancelada'), (8, 'Debitado'), (9, 'Retenção temporária')], default=1, max_length=255, verbose_name='Status'),
        ),
    ]
