# Generated by Django 2.2.1 on 2019-09-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billet', '0004_auto_20190907_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billet',
            name='status',
            field=models.CharField(choices=[('1', 'Aguardando pagamento'), ('2', 'Em análise'), ('3', 'Pago'), ('4', 'Disponível'), ('5', 'Em disputa'), ('6', 'Devolvido'), ('7', 'Cancelado'), ('8', 'Debitado'), ('9', 'Retenção temporária')], default='1', max_length=255, verbose_name='Status'),
        ),
    ]
