# Generated by Django 2.2.10 on 2020-05-14 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do banco')),
                ('agency', models.CharField(max_length=255, verbose_name='Agencia')),
                ('account', models.CharField(max_length=255, verbose_name='Conta com digito')),
                ('fullname', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('types', models.CharField(choices=[('cc', 'Conta-corrente'), ('cp', 'Conta-poupança')], max_length=255, verbose_name='Tipo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['name', '-created_at'],
                'permissions': [('list_bank', 'Pode Listar Bancos')],
            },
        ),
    ]
