# Generated by Django 2.2.10 on 2020-05-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='operation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Operação'),
        ),
    ]
