# Generated by Django 2.2.10 on 2020-08-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_bank_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF'),
        ),
    ]
