# Generated by Django 2.2.10 on 2024-03-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20200807_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='pix',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pix'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='account',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Conta com digito'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='agency',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Agencia'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='types',
            field=models.CharField(blank=True, choices=[('cc', 'Conta-corrente'), ('cp', 'Conta-poupança')], max_length=255, null=True, verbose_name='Tipo'),
        ),
    ]
