# Generated by Django 2.2.10 on 2020-05-13 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_profile', '0002_profile_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='config',
        ),
        migrations.AddField(
            model_name='profile',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pay_method',
            field=models.CharField(default='billet', max_length=255, verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('username', models.CharField(max_length=255, verbose_name='Usuário')),
                ('password', models.CharField(max_length=255, verbose_name='Senha')),
                ('value', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Valor')),
                ('points', models.PositiveSmallIntegerField(default=1, verbose_name='Pontos')),
                ('expiration', models.DateField(verbose_name='Expiração')),
                ('status', models.CharField(default='active', max_length=255, verbose_name='Status')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='panel.Panel', verbose_name='Painel')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='custom_profile.Profile', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['username', '-created_at'],
                'permissions': [('list_profile_user', 'Pode Listar Usuários do Perfil')],
            },
        ),
    ]
