# Generated by Django 2.2.10 on 2020-05-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_profile', '0004_auto_20200513_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(help_text='Nome e sobrenome', max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('waiting_payment', 'Aguardando pagamento'), ('expired', 'Vencido'), ('in_test', 'Em teste')], default='in_test', max_length=255, verbose_name='Status'),
        ),
    ]
