# Generated by Django 2.2.10 on 2020-05-15 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_profile', '0005_auto_20200514_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileuser',
            options={'ordering': ['username', '-created_at'], 'permissions': [('list_profileuser', 'Pode Listar Usuários do Perfil')], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
