# Generated by Django 2.2.10 on 2020-05-19 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_profile', '0006_auto_20200515_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileuser',
            options={'ordering': ['expiration', '-created_at'], 'permissions': [('list_profileuser', 'Pode Listar Usuários do Perfil')], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
